#!/usr/bin/env node
// Lovable Engineering Agent runner. Executes an edit/build/test loop for a
// single work order, then opens a PR. Progress is streamed back to the
// platform via signed callbacks. Runs inside GitHub Actions — no platform
// code ever runs here.
import { execSync } from "node:child_process";
import { createHmac } from "node:crypto";
import { writeFileSync, existsSync, mkdirSync } from "node:fs";

const env = process.env;
const REQUIRED = ["WORK_ORDER_ID", "BRANCH", "TITLE", "GITHUB_TOKEN", "GITHUB_REPOSITORY"];
for (const k of REQUIRED) if (!env[k]) throw new Error(`Missing required env: ${k}`);

const [owner, repo] = env.GITHUB_REPOSITORY.split("/");
const runUrl = env.GITHUB_SERVER_URL && env.GITHUB_RUN_ID
  ? `${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}`
  : null;

async function callback(event, status) {
  const url = env.PLATFORM_CALLBACK_URL;
  if (!url) { console.log("[callback skipped: PLATFORM_CALLBACK_URL not set]", event); return; }
  const body = JSON.stringify({
    workOrderId: env.WORK_ORDER_ID,
    externalRunId: env.GITHUB_RUN_ID ?? null,
    externalRunUrl: runUrl,
    event,
    status,
  });
  const headers = { "content-type": "application/json", "x-agent-id": "lovable" };
  if (env.PLATFORM_CALLBACK_SECRET) {
    headers["x-agent-signature"] = "sha256=" +
      createHmac("sha256", env.PLATFORM_CALLBACK_SECRET).update(body).digest("hex");
  }
  try {
    const res = await fetch(url, { method: "POST", headers, body });
    if (!res.ok) console.error("[callback non-2xx]", res.status, (await res.text()).slice(0, 200));
  } catch (e) { console.error("[callback failed]", e); }
}

function git(args, opts = {}) {
  const out = execSync(`git ${args}`, { stdio: "pipe", encoding: "utf8", ...opts });
  return typeof out === "string" ? out.trim() : "";
}

async function githubApi(path, init = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${env.GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...(init.headers ?? {}),
    },
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`GitHub ${path} ${res.status}: ${text.slice(0, 300)}`);
  return text ? JSON.parse(text) : {};
}

async function run() {
  await callback(
    { level: "info", step: "started", message: `Engineering agent started for #${env.WORK_ORDER_NUMBER ?? env.WORK_ORDER_ID}` },
    { state: "running" },
  );

  // --- Placeholder edit step ---
  // The full edit/build/test loop wiring lands in a follow-up. For now the
  // agent records the work order intent so the branch has a real commit,
  // then opens a PR. This exercises the whole platform pipeline end-to-end.
  if (!existsSync(".factory")) mkdirSync(".factory", { recursive: true });
  const notesPath = `.factory/work-order-${env.WORK_ORDER_ID}.md`;
  writeFileSync(notesPath, [
    `# Work Order ${env.WORK_ORDER_NUMBER ?? ""}: ${env.TITLE}`,
    "",
    "## Description",
    env.DESCRIPTION || "(none)",
    "",
    "## Acceptance",
    env.ACCEPTANCE || "(none)",
    "",
    `Generated by the Lovable Engineering Agent on ${new Date().toISOString()}.`,
    "",
  ].join("\n"));

  git(`config user.email "engineering-agent@users.noreply.github.com"`);
  git(`config user.name "Lovable Engineering Agent"`);

  // Ensure the working branch exists locally and includes latest tooling from
  // the default branch. Handles pre-existing branches created before the runner
  // script was installed.
  const defaultBranchName = (await githubApi(`/repos/${owner}/${repo}`)).default_branch;
  git(`fetch origin ${env.BRANCH}:refs/remotes/origin/${env.BRANCH}`, { stdio: "ignore" });
  const hasRemote = (() => {
    try { git(`rev-parse --verify refs/remotes/origin/${env.BRANCH}`); return true; }
    catch { return false; }
  })();
  if (hasRemote) {
    git(`checkout -B ${env.BRANCH} refs/remotes/origin/${env.BRANCH}`);
    try { git(`merge --no-edit origin/${defaultBranchName}`); }
    catch { /* leave to fail on push if truly divergent */ }
  } else {
    git(`checkout -B ${env.BRANCH}`);
  }

  git(`add ${notesPath}`);
  try {
    git(`commit -m "chore(factory): record work order ${env.WORK_ORDER_NUMBER ?? env.WORK_ORDER_ID}"`);
  } catch { /* nothing to commit */ }

  const commitSha = git("rev-parse HEAD");
  git(`push origin HEAD:${env.BRANCH}`);


  await callback(
    { level: "info", step: "iteration", message: "Committed working changes", metadata: { commit: commitSha } },
    { state: "running", commitSha },
  );

  // --- Open PR ---
  const defaultBranch = defaultBranchName;

  let pull;
  try {
    pull = await githubApi(`/repos/${owner}/${repo}/pulls`, {
      method: "POST",
      body: JSON.stringify({
        title: `[WO-${env.WORK_ORDER_NUMBER ?? ""}] ${env.TITLE}`,
        head: env.BRANCH,
        base: defaultBranch,
        body: [
          `Work order id: \`${env.WORK_ORDER_ID}\``,
          "",
          "## Description",
          env.DESCRIPTION || "(none)",
          "",
          "## Acceptance",
          env.ACCEPTANCE || "(none)",
        ].join("\n"),
      }),
    });
  } catch (e) {
    // If PR already exists, fetch it.
    const existing = await githubApi(
      `/repos/${owner}/${repo}/pulls?head=${owner}:${encodeURIComponent(env.BRANCH)}&state=open`,
    );
    if (Array.isArray(existing) && existing.length > 0) pull = existing[0];
    else throw e;
  }

  await callback(
    { level: "info", step: "pr_opened", message: `Pull request #${pull.number} opened`, metadata: { pr: pull.number } },
    { state: "running", pullRequestUrl: pull.html_url, commitSha },
  );

  await callback(
    { level: "info", step: "succeeded", message: "Engineering agent completed" },
    { state: "succeeded", pullRequestUrl: pull.html_url, commitSha },
  );
}

run().catch(async (err) => {
  console.error(err);
  await callback(
    { level: "error", step: "failed", message: String(err?.message ?? err).slice(0, 1900) },
    { state: "failed", failureReason: String(err?.message ?? err).slice(0, 1900) },
  );
  process.exit(1);
});
